version: "3"
services:

  app:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./devenv/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./app/public:/app/public:cached
    depends_on:
      - php

  php:
    build: ./devenv/php/
    volumes:
      - ./app:/app:cached

  mongo:
    image: mongo
    volumes:
      - ./devenv/mongo/data:/data/db:cached
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    #restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
